networks:
  dev:
services:
  nginx:
      image: nginx:alpine
      container_name: fullapp-nginx
      ports:
        - "80:80"
      volumes:
        - './nginx.conf:/etc/nginx/nginx.conf'
      depends_on:
        - backend
        - frontend
      networks:
        - dev
  
  backend:
    build:
      context: ./backend
    environment:
      - secretKey=ullapp
    networks:
      - dev

  frontend:
    build:
      context: ./spa
    networks:
      - dev
  
  
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage: {}
